### ISSUE TITLE
net6: typo preventing rendering of Scripts section

### ISSUE THREAD

**Issue by kroppt** [psauthor/MeterReader#22]
The registration page, provided as a part of the `Microsoft.AspNetCore.Identity.UI` library, requires the rendering of the `Scripts` section. Currently, on the latest version of net6, it fails to render that, preventing registration.

This line of code should be rendering the `Scripts` section, not the `Script` section.

https://github.com/psauthor/MeterReader/blob/fb37921b8ed4d865f022ac8e75bb4850634f8b15/src/MeterReader/Pages/Shared/_Layout.cshtml#L52

**Comment by shawnwildermuth** [comment]
Thanks, i'll fix it.

**Comment by shawnwildermuth** [comment]
Fixed in net6 branch (isn't wrong in the main branch - .NET 5):

See the update:

https://github.com/psauthor/MeterReader/blob/00b6d88505984bdfcf5c8688b3e08a2b6ae9ec3d/src/MeterReader/Pages/Shared/_Layout.cshtml#L52
